### ISSUE TITLE
مشکل در فصل اول

### ISSUE THREAD

**Issue by KevinScruff** [Noah1001000/clean-code-persian#14]
<div dir="ltr">
<p>سلام یک مشکلی وجود داره توی فصل اول که به خاطر ادرس دهی نشدن اونه</p>
<img src="https://user-images.githubusercontent.com/43755665/79433662-a8d3a300-7fe2-11ea-8b9e-2135f069c4a9.png">

</div>

**Comment by Noah1001000** [comment]
نمیدونم چطور باید حلش کنم

**Comment by KevinScruff** [comment]
> نمیدونم چطور باید حلش کنم

حلش کردم و پول ریکوئست زدم
