### ISSUE TITLE
وجود نداشتن عکس ها 

### ISSUE THREAD

**Issue by KevinScruff** [Noah1001000/clean-code-persian#16]
<div dir="rtl">
<p>عکس های مقدمه و فصل یک وجود ندارن</p>
<p dir="ltr"><a href="https://github.com/Noah1001000/clean-code-persian/blob/master/0_Introduction/picture%200.1.png">https://github.com/Noah1001000/clean-code-persian/blob/master/0_Introduction/picture%200.1.png</a></p>
<p align="center">
<img src="https://user-images.githubusercontent.com/43755665/79436780-90658780-7fe6-11ea-8eaa-8cd4309140d2.png">
</p>
</div><p align="center">
<img src="https://user-images.githubusercontent.com/43755665/79436909-b854eb00-7fe6-11ea-9864-49ffadd09592.png">
</p>

**Comment by Noah1001000** [comment]
این رو درستش میکنم. ولی الان به سیستمم دسترسی ندارم
