### ISSUE TITLE
ذخیره زبان اصلی کتاب

### ISSUE THREAD

**Issue by itsamirrezah** [Noah1001000/clean-code-persian#19]
اولا مرسی از این ایده خوب و کمکی که همه دوستان می‌کنند.
یه پیشنهاد کوچک دارم: بهتر نیست ترجمه دوستان با متن اصلی کتاب جایگزین نشه؟‌ اینطوری تصحیح ترجمه‌ها برای افرادی که بعدا به پروژه اضافه می‌شن راحت تر میشه.

**Comment by Noah1001000** [comment]
اگر منظورتون اینه که فایل زبان اصلی رو هم جداگانه بگذاریم میشه روش کار کرد. ولی فکر نکنم کسایی که قصد اصلاح داشته باشند به زبان اصلی نگاه کنن. بهترین راه اینه که اولین ترجمه بهترین ترجمه باشه و بقیه فقط غلط های املایی و تایپی رو اصلاح کنند یا جاهایی که ترجمه خیلی خشک شده رو روان تر کنند. 
ایده خوبیه ولی یکم زمان بره . اگر خودت زحمتشو بکشی استقبال میکنم

**Comment by itsamirrezah** [comment]
فکر نکنم خیلی زمان بر بشه. کافیه متن اصلی هر فصل در پوشه مرتبط به خودش اضافه بشه.
اگه به نظرت مفیده، خوشحال میشم اینکارو انجام بدم.

**Comment by Noah1001000** [comment]
اره حتما مفیده وخوشحال میشم انجامش بدی ولی چند تا نکته：
۱-نمیشه کل فصل رو یکدفعه کپی کرد چون شماره صفحه و چیز هایی که بالای صفحه نوشته شده هم کپی میشه. باید صفحه صفحه کپی کرد
۲-پاورقی هارو باید بگذاریم توی پرانتز جلو کلمه
۳- کد ها کلا به هم میریزه و درست کردنش کلی وقت میبره, البته اگه با کد ادیتور انجام بدی زودتر میشه
۳- هایلایت کردن کد ها هم یه داستانیه برای خودش
۴-عکس ها رو هم باید ذخیره کنی و بگذاری توی پوشه مربوط به فصل

به خاطر اینها گفتم زمان بره ولی اگر انجام بدی خوشحال میشم. یه قدم بردار شاید خودم هم اومدم کمکت
موفق باشی

**Comment by Noah1001000** [comment]
حل شد
