### ISSUE TITLE
آیا واقعا لازمه؟

### ISSUE THREAD

**Issue by guftall** [Noah1001000/clean-code-persian#23]
البته که وقتی که میذارید ارزشمنده، اینکه نسبت به پیشرفت جامعه برنامه نویسی و گسترش فعالیت های گروهی احساس مسئولیت میکنید.

اما آیا یکی وجود داره که فکر میکنه به سطحی رسیده که باید کد تمیز بنویسه، و هنور توی منابع فارسی دنبال یادگیریه؟

**Comment by sajaddp** [comment]
کد تمیز نوشتن یک پیش نیازه نه یک سطح (:

**Comment by Noah1001000** [comment]
کد نویسی تمیز از مهم ترین چیز هاییه که برنامه نویس ها باید یاد بگیرند. شاید خیلی ها احساس نیاز نکنند ولی ما کار خودمون رو میکنیم

**Comment by guftall** [comment]
@sajaddp پیشنهاد میکنم کتاب رو یکبار بخونید.

@Noah1001000 موفق باشید، بهرحال کاری انجام دادن بهتر از هیچ کاری نکردنه
