### ISSUE TITLE
Duplicate files in 0_introduction(completed) folder

### ISSUE THREAD

**Issue by Kaaveh** [Noah1001000/clean-code-persian#38]
In the 0_introduction(completed) folder, there are two files with the same content: introduction.md and README.md. I suggest that remove README.md.

**Comment by Noah1001000** [comment]
راستش زیاد دوست ندارم که readme خالی باشه.
مخصوصا برای مقدمه که زیاد طولانی نیست. چون راحت میتونن همونجا بخوننش.
در هر صورت فکر نکنم مشکل حادی باشه.
ممنون که توجه کردی

**Comment by Kaaveh** [comment]
Alright! 👌🏻
