### ISSUE TITLE
Some sections in chapter 1 won't be translated

### ISSUE THREAD

**Issue by Kaaveh** [Noah1001000/clean-code-persian#39]
At the end of translation for chapter 1, these sections won't be translated: 

We Are Authors.....................................................................................13
The Boy Scout Rule .............................................................................14
Prequel and Principles..........................................................................15
Conclusion............................................................................................15

**Comment by Noah1001000** [comment]
از سهل انگاری خودمه.
رسیدگی میکنم.
سپاس فراوان
