### ISSUE TITLE
حذف یک پوشه اضافی

### ISSUE THREAD

**Issue by hamedtakmil** [Noah1001000/clean-code-persian#42]
لطفاً پوشه
.idea
رو به گیت ایگنور اضافه کنید که نیاد توی مخزن کد

**Comment by Kaaveh** [comment]
Noah did it. Please, someone, close this issue.

**Comment by Noah1001000** [comment]
دیروز گذاشتمش توی گیت ایگنور ولی ظاهرا هنوز هستش

**Comment by Kaaveh** [comment]
Also, you must untrak this folder from git. Use:

`git rm --cached -r mydirectory`
