### ISSUE TITLE
باز نشدن فصل ها

### ISSUE THREAD

**Issue by SEFiiD** [Noah1001000/clean-code-persian#49]
درود
فصل اول و دوم و سوم  کلا ۴۰۴ میده

**Comment by Noah1001000** [comment]
سلام . ظاهرا لینک ها مشکلی نداره
میشه بگید دقیقا روی چه فصل و بخشی کلیک کردید

**Comment by Noah1001000** [comment]
همه لینک های فصل اول رو امتحان کردم ولی مشکلی نداشت.
نمیدونم. احتمالا جای دیگه ای مشکل داره.
ممنون که گزارش دادی

**Comment by Noah1001000** [comment]
لینک های فصل دوم هم مشکل نداشت

**Comment by SEFiiD** [comment]
لینک های درون فایل های
