### ISSUE TITLE
آیا خود کتاب به صورت آزاد منتشر شده است؟

### ISSUE THREAD

**Issue by amirmojiry** [Noah1001000/clean-code-persian#59]
اول باید تشکر کنم از پروژه‌ی خیلی خوبی که شروع کردید.
سوالی که دارم اینه که خود کتاب به صورت آزاد منتشر شده؟ و در این صورت کجا می شه پیداش کرد؟

**Comment by Noah1001000** [comment]
خوشحالم که نظرتون رو جلب کرده.
اگر منظورتون از خود کتاب نسخه انگلیسی اونه نه. کتاب به صورت آزاد منتشر نشده. ولی به 
دلیل نبود قوانین کپی رایت با یک سرچ ساده میتونید اون رو دانلود کنید.
من از سایت 
pdfdrive.com
 اون رو دانلود کردم ولی فکر کنم توی سایت های فارسی هم زیاد باشه.
