### ISSUE TITLE
ساخت وب پیج (پیشنهاد)

### ISSUE THREAD

**Issue by payam-zahedi** [Noah1001000/clean-code-persian#63]
پیشنهاد من اینه که کلیت این کتاب به صورت یک صفحه وب پیاده سازی بشه. با این قابلیت کاربر خیلی راحت میتونه:

- منو و صفحات همیشه در دسترس داشته باشه
- بین صفحات نویگیشن کنه
- واسط کاربری بهتری رو داشته باشه (css) 
-  و ...

من توسعه دهنده وب نیستم و در این شاخه تخصص کافی رو ندارم اما تا حدودی در مورد github pages مطالعه داشتم. فکر میکنم میشه به صورت رایگان یه همپچین صفحه ای روی این بستر  بارگذاری کرد

ممنون از کار زیباتون

**Comment by HamadTheIronside** [comment]
توی این مورد میتونین رو من حساب باز کنین

**Comment by Noah1001000** [comment]
پیشنهاد خوبیه. خودم هم بهش فکر کردم.
فکر کنم خود گیتهاب امکاناتی برای این کار داشته باشه ولی زیاد اشنا نیستم

**Comment by Noah1001000** [comment]
اگر بتونید این کارو انجام بدید که خیلی ازتون سپاسگذار میشم
فقط من رو در جریان بگذارید

**Comment by HamadTheIronside** [comment]
حتما درجریانتون میزارم، ی بررسی کلی میکنم و خبرتون میدم که دقیقا چکار میکنم.

**Comment by mshahamirian** [comment]
بله از طريق github pages این امکان میسر هست ضمن اینکه میتوان به یک دامین اختصاصی نیست متصل کرد
Ex: cleancodepersian.github.io
Customized domain Ex: cleancodepersian.ir

**Comment by mshahamirian** [comment]
تنها کافیه از یک static site builder با پشتیبانی مارک داون استفاده بشه و مطالب جایگذاری بشن

**Comment by payam-zahedi** [comment]
@mshahamirian 
دوستان همین حالا هم از مارک داون استفاده میکنن.
سوال اینه که اگه از این static site builder ها استفاده کنیم 
وقتی متن یک فایل تغییر میکنه آیا محتوای سایت هم تغییر میکنه و یا نه باید حتما از سایت یه build گرفته بشه ؟ 
@HamadTheIronside

**Comment by Noah1001000** [comment]
همونطور که از اسمش پیداست فکر نکنم همراه با تغییر گیتهاب تغییر کنه.نظر من اینه که یه سایت اختصاصی برای کتاب بزنیم که میتونیم یه رابط خوب براش بسازیم که مشارکت و اصلاح کتاب راحت تر پیش بره.
خلاصه دستمون برای این کار ها باز تره.
خودم میتونم این کارو انجام بدم ولی متاسفانه تجربه زیادی ندارم و نیاز به راهنمایی دارم . اگر کسی میتونه کمکم کنه با کمال میل انجامش میدم

**Comment by mshahamirian** [comment]
@payam-zahedi برای استفاده از گیت‌های پیجز بایستی یک ریپازیتوری ایجاد کرد با اسم آدرسی که میخواید.
بطور مثال توی پروفایل من که قبلا این کار رو کردم ریپازیتوری هست به اسم mshahamirian.github.io که قبلا توسط آدرس https://mshahamirian.github.io در دسترس بود.

**Comment by mshahamirian** [comment]
حتی میشه کل پروژه ترجمه رو منتثل کرد به ریپوی گیت‌هاب پیجز و مستقیم پروژه روی اون ادامه پیدا کنه

**Comment by HamadTheIronside** [comment]
ببینید دوتا راه حل داریم
یکی اینه که Nextjs استفاده کنیم که کلا کنترلش دست ما باشه ولی وقت میگیره و نیازه build گرفته بشه که کار سختی نیست این‌کار و کلا یه کامند به npm میشه اضافه کرد و اتومات کرد
راه حل دومی که این اسونتره اینه که از گیت‌هاب پیجز و تم هاش استفاده کنیم که پیشنهادی من [minima](https://github.com/jekyll/minima) هست. و ادیت کردنشون هم آسونه و نیازه به build گرفتن و این داستانا نیست و با رعایت کردن یه سری موارد خاص میشه SEO خیلی خوبی گرفت.
من اخیرا لپتاپم خراب شده و یه سری مشکلات داشتم نتونستم حرکت بزنم. احتمالا امشب اوکی بشه اگه شد تا فردا ی pr میزنم تا ببینین چطور میشه با تم minima.

**Comment by Noah1001000** [comment]
گیتهاب پیجز به نظر گزینه خوبیه. سعی میکنم تا چند روز آینده درستش کنم. ممنون از همه.
اگه نکته دیگه ای بود بهم ایمیل برنید

**Comment by payam-zahedi** [comment]
دوستان میتونیم از ابزار هایی هم برای ساخت سایت استاتیک استفاده کرد مثل 
[docusaurus 2](https://v2.docusaurus.io/)
و باز هم میشه این سایت رو github pages منتشر کرد
