### ISSUE TITLE
دانلود پی دی اف

### ISSUE THREAD

**Issue by arjahanifard** [Noah1001000/clean-code-persian#86]
سلام 
پی دی اف کتاب رو چطور دانلود بکنم

**Comment by Noah1001000** [comment]
سلام
از طریق اینترنت:)
https://www.ebooksworld.ir/post/index/267/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8-clean-code-a-handbook-of-agile-software-craftsmanship

**Comment by arjahanifard** [comment]
> سلام
> از طریق اینترنت:)
> https://www.ebooksworld.ir/post/index/267/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8-clean-code-a-handbook-of-agile-software-craftsmanship

دوست عزیز منظورم پروژه ترجمه شماست وقتی برای پروژه شما پیام میزارم یعنی منظورم پی دی اف شماست وگرنه پیدا کردن نسخه انگلیسی اش که کاری نداره

**Comment by arm-ahh** [comment]
> > سلام
> > از طریق اینترنت:)
> > https://www.ebooksworld.ir/post/index/267/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8-clean-code-a-handbook-of-agile-software-craftsmanship
> 
> دوست عزیز منظورم پروژه ترجمه شماست وقتی برای پروژه شما پیام میزارم یعنی منظورم پی دی اف شماست وگرنه پیدا کردن نسخه انگلیسی اش که کاری نداره

قبلا خیلی ها نسخه انگلیسیش رو از من خواسته بودند و من هم فکر کردم منظور شما همونه
فعلا  پروزه ما نسخه پی دی اف نداره و احتمالا نخواهد داشت. چون احتمال تغییر اون زیاده و آپدیت نگه داشتن پی دی اف سخته
فقط میتونید کتاب رو از گیتهاب یا سایت زیر مطالعه کنید:
https://codetamiz.vercel.app/

**Comment by Noah1001000** [comment]
> > سلام
> > از طریق اینترنت:)
> > https://www.ebooksworld.ir/post/index/267/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8-clean-code-a-handbook-of-agile-software-craftsmanship
> 
> دوست عزیز منظورم پروژه ترجمه شماست وقتی برای پروژه شما پیام میزارم یعنی منظورم پی دی اف شماست وگرنه پیدا کردن نسخه انگلیسی اش که کاری نداره

قبلا خیلی ها نسخه انگلیسیش رو از من خواسته بودند و من هم فکر کردم منظور شما همونه
فعلا پروزه ما نسخه پی دی اف نداره و احتمالا نخواهد داشت. چون احتمال تغییر اون زیاده و آپدیت نگه داشتن پی دی اف سخته
فقط میتونید کتاب رو از گیتهاب یا سایت زیر مطالعه کنید:
https://codetamiz.vercel.app/

**Comment by sina-devel** [comment]
@Noah1001000 
میشه یه اسکریپت نوشت که تبدیل به پی دی اف کنه

**Comment by Noah1001000** [comment]
> @Noah1001000
> میشه یه اسکریپت نوشت که تبدیل به پی دی اف کنه

زیاد در موردش اطلاع ندارم
فکر کنم چون هم انگلیسی داره هم فارسی به مشکل بخوریم چون متن 
 کتاب باید راست چین باشه و کد هاچپ چین
ولی اگه راهی باشه که کد اچ تی ام ال رو مستقیم به پی دی اف تبدیل کنیم فکر کنم بشه یه کارایی کرد
