### ISSUE TITLE
Is there a PDF version of this?

### ISSUE THREAD

**Issue by fmv1992** [Noah1001000/clean-code-persian#93]
Hey there, first of all: thanks for this.

I've been studying فارسی (as a second language) and I code, so this book is a blessing!

Is there a way to get a PDF version of this?

Have a great week!

**Comment by Kaaveh** [comment]
Hi
Unfortunately, no. You can use similar books like this:

https://github.com/sabajamalian/debugging-teams-fa

**Comment by fmv1992** [comment]
Thanks, no problem, the html is great too! Thanks for making this.
